import { useState, type FormEvent } from 'react'
import { Activity, LoaderCircle, X } from 'lucide-react'
import apiClient from '../../api/client'
import type { Device } from '../../types/device'

export default function SimulateHeartbeatModal({ device, onClose, onUpdated }: { device: Device | null; onClose: () => void; onUpdated: (device: Device) => void }) {
  const [battery, setBattery] = useState(72); const [charging, setCharging] = useState(false); const [network, setNetwork] = useState('Wi-Fi'); const [vpn, setVpn] = useState(false); const [root, setRoot] = useState(false); const [developer, setDeveloper] = useState(false); const [usb, setUsb] = useState(false); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState('')
  if (!device) return null
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSaving(true); setError(''); try { const { data } = await apiClient.post<Device>(`/devices/${device.id}/heartbeat`, { battery_level: battery, is_charging: charging, network_type: network, vpn_active: vpn, root_detected: root, developer_options: developer, usb_debugging: usb }); onUpdated(data); onClose() } catch { setError('The heartbeat could not be sent.') } finally { setIsSaving(false) } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="heartbeat-title"><div className="w-full max-w-lg rounded-2xl border border-border bg-surface shadow-2xl shadow-black/50"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/15 text-accent"><Activity className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">Test harness</p><h2 className="mt-1 text-lg font-semibold text-slate-50" id="heartbeat-title">Simulate heartbeat</h2></div></div><button className="rounded-lg p-2 text-slate-500 hover:bg-card hover:text-slate-100" type="button" onClick={onClose} aria-label="Close modal"><X className="h-5 w-5" /></button></div><form className="space-y-5 p-6" onSubmit={submit}><div><div className="mb-2 flex justify-between text-sm font-medium text-slate-300"><label htmlFor="battery-level">Battery level</label><span className="font-mono text-accent">{battery}%</span></div><input className="w-full accent-emerald-400" id="battery-level" type="range" min="0" max="100" value={battery} onChange={(event) => setBattery(Number(event.target.value))} /></div><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Is charging" value={charging} onChange={setCharging} /><Toggle label="VPN active" value={vpn} onChange={setVpn} /><Toggle label="Root detected" value={root} onChange={setRoot} danger /><Toggle label="Developer options" value={developer} onChange={setDeveloper} /><Toggle label="USB debugging" value={usb} onChange={setUsb} /></div><label className="block text-sm font-medium text-slate-300">Network type<select className="mt-2 w-full rounded-lg border border-border bg-bg px-3 py-2.5 text-slate-100 outline-none focus:border-primary" value={network} onChange={(event) => setNetwork(event.target.value)}><option>Wi-Fi</option><option>5G</option><option>LTE</option></select></label>{error && <p className="rounded-lg border border-red-400/30 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p>}<div className="flex justify-end gap-3 border-t border-border pt-5"><button className="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-400 hover:text-slate-100" type="button" onClick={onClose}>Cancel</button><button className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-60" type="submit" disabled={isSaving}>{isSaving && <LoaderCircle className="h-4 w-4 animate-spin" />}Send heartbeat</button></div></form></div></div>
}

function Toggle({ label, value, onChange, danger = false }: { label: string; value: boolean; onChange: (value: boolean) => void; danger?: boolean }) { return <label className="flex cursor-pointer items-center justify-between rounded-lg border border-border bg-bg px-3 py-3 text-sm text-slate-300">{label}<input className={`h-4 w-4 ${danger ? 'accent-red-400' : 'accent-emerald-400'}`} type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} /></label> }