import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Archive, CheckCircle2, ChevronDown, CircleUserRound, Database, FileText, RefreshCw, Search, ShieldAlert, ShieldCheck, Users, X } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import apiClient from '../api/client'
import { useAuth } from '../context/AuthContext'
import type { AdminAuditLog, AdminUser, GlobalStats } from '../types/admin'

type AdminTab = 'users' | 'audit-logs'

const formatBytes = (bytes: number) => { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`; if (bytes < 1024 ** 3) return `${(bytes / 1024 ** 2).toFixed(1)} MB`; return `${(bytes / 1024 ** 3).toFixed(1)} GB` }
const tabFromPath = (pathname: string): AdminTab => pathname.endsWith('/audit-logs') ? 'audit-logs' : 'users'

export default function Admin() {
  const { user: currentUser } = useAuth()
  const location = useLocation()
  const navigate = useNavigate()
  const [users, setUsers] = useState<AdminUser[]>([])
  const [stats, setStats] = useState<GlobalStats | null>(null)
  const [auditLogs, setAuditLogs] = useState<AdminAuditLog[]>([])
  const [search, setSearch] = useState('')
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')
  const [selectedLog, setSelectedLog] = useState<AdminAuditLog | null>(null)
  const [updatingUserId, setUpdatingUserId] = useState<string | null>(null)
  const activeTab = tabFromPath(location.pathname)

  const loadData = useCallback(async () => {
    setIsLoading(true); setError('')
    try {
      const [usersResponse, statsResponse, auditResponse] = await Promise.all([apiClient.get<AdminUser[]>('/admin/users'), apiClient.get<GlobalStats>('/admin/stats'), apiClient.get<AdminAuditLog[]>('/admin/audit-logs')])
      setUsers(usersResponse.data); setStats(statsResponse.data); setAuditLogs(auditResponse.data)
    } catch { setError('Governance data could not be loaded. Check the API connection and try again.') }
    finally { setIsLoading(false) }
  }, [])
  useEffect(() => { void loadData() }, [loadData])

  const filteredUsers = useMemo(() => users.filter((item) => `${item.email} ${item.full_name ?? ''}`.toLowerCase().includes(search.trim().toLowerCase())), [search, users])
  const filteredLogs = useMemo(() => auditLogs.filter((item) => `${item.action} ${item.ip_address ?? ''} ${JSON.stringify(item.details)}`.toLowerCase().includes(search.trim().toLowerCase())), [auditLogs, search])
  const changeTab = (tab: AdminTab) => { setSearch(''); navigate(`/admin/${tab}`) }
  const updateStatus = async (target: AdminUser) => {
    if (target.id === currentUser?.id) return
    setUpdatingUserId(target.id); setError('')
    try { const { data } = await apiClient.put<AdminUser>(`/admin/users/${target.id}/status`, { is_active: !target.is_active }); setUsers((current) => current.map((item) => item.id === target.id ? data : item)) }
    catch { setError('The user status could not be updated.') }
    finally { setUpdatingUserId(null) }
  }

  return <section><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] text-blue-300"><ShieldCheck className="h-3.5 w-3.5" />Platform Governance</div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-50">Admin Console</h1><p className="mt-3 text-slate-400">Manage platform access and inspect the global audit ledger.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-slate-300 hover:bg-card hover:text-slate-100 disabled:opacity-60" type="button" onClick={() => void loadData()} disabled={isLoading}><RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />Refresh governance data</button></div>
    <div className="mb-6 grid gap-4 md:grid-cols-3"><OverviewCard label="Total profiles" value={stats?.total_profiles} detail={`${stats?.active_profiles ?? 0} active · ${stats?.trash_profiles ?? 0} in trash`} icon={FileText} /><OverviewCard label="Total fleet" value={stats?.total_devices} detail={`${stats?.online_devices ?? 0} online · ${stats?.offline_devices ?? 0} offline`} icon={Activity} /><OverviewCard label="Storage consumed" value={stats ? formatBytes(stats.total_storage_bytes) : undefined} detail={`${stats?.total_backups ?? 0} backup snapshots`} icon={Database} /></div>
    <div className="mb-6 flex flex-col gap-3 rounded-xl border border-border bg-surface p-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex rounded-lg bg-bg p-1"><button className={`inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition ${activeTab === 'users' ? 'bg-card text-slate-100 shadow' : 'text-slate-500 hover:text-slate-200'}`} type="button" onClick={() => changeTab('users')}><Users className="h-4 w-4" />User Management</button><button className={`inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition ${activeTab === 'audit-logs' ? 'bg-card text-slate-100 shadow' : 'text-slate-500 hover:text-slate-200'}`} type="button" onClick={() => changeTab('audit-logs')}><Archive className="h-4 w-4" />Global Audit Trail</button></div><label className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-slate-600" /><input className="w-full rounded-lg border border-border bg-bg py-2 pl-9 pr-3 text-sm text-slate-100 outline-none placeholder:text-slate-600 focus:border-primary sm:w-80" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={activeTab === 'users' ? 'Search by email or name' : 'Search actions, IPs, or details'} aria-label={activeTab === 'users' ? 'Search users' : 'Search audit logs'} /></label></div>
    {error && <div className="mb-6 flex items-center justify-between rounded-xl border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-200" role="alert">{error}<button className="inline-flex items-center gap-2 font-semibold" type="button" onClick={() => void loadData()}>Retry <RefreshCw className="h-4 w-4" /></button></div>}
    {isLoading ? <div className="h-80 animate-pulse rounded-xl border border-border bg-surface" /> : activeTab === 'users' ? <UserTable users={filteredUsers} currentUserId={currentUser?.id} updatingUserId={updatingUserId} onToggle={(user) => void updateStatus(user)} /> : <AuditTable logs={filteredLogs} onInspect={setSelectedLog} />}
    <AuditDetailsModal log={selectedLog} onClose={() => setSelectedLog(null)} />
  </section>
}

function OverviewCard({ label, value, detail, icon: Icon }: { label: string; value?: number | string; detail: string; icon: typeof Activity }) { return <article className="rounded-xl border border-border bg-surface p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold text-slate-50">{value ?? '—'}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span></div></article> }

function UserTable({ users, currentUserId, updatingUserId, onToggle }: { users: AdminUser[]; currentUserId?: string; updatingUserId: string | null; onToggle: (user: AdminUser) => void }) { return <div className="overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-border bg-bg/60 text-[11px] uppercase tracking-wider text-slate-600"><tr><th className="px-5 py-4 font-semibold">User</th><th className="px-5 py-4 font-semibold">Role</th><th className="px-5 py-4 font-semibold">Status</th><th className="px-5 py-4 font-semibold">Verified</th><th className="px-5 py-4 font-semibold">Joined</th><th className="px-5 py-4 text-right font-semibold">Access</th></tr></thead><tbody className="divide-y divide-border/70">{users.map((user) => { const isSelf = user.id === currentUserId; return <tr className="text-sm text-slate-300" key={user.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-card text-slate-400"><CircleUserRound className="h-4 w-4" /></span><div><p className="font-semibold text-slate-100">{user.full_name || 'Unnamed user'}{isSelf && <span className="ml-2 text-xs font-normal text-primary">You</span>}</p><p className="mt-1 text-xs text-slate-500">{user.email}</p></div></div></td><td className="px-5 py-4 text-xs font-semibold uppercase tracking-wider text-slate-400">{user.role}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 text-xs font-semibold ${user.is_active ? 'text-accent' : 'text-red-300'}`}>{user.is_active ? <CheckCircle2 className="h-4 w-4" /> : <ShieldAlert className="h-4 w-4" />}{user.is_active ? 'Active' : 'Suspended'}</span></td><td className="px-5 py-4 text-xs text-slate-400">{user.is_verified ? 'Verified' : 'Unverified'}</td><td className="px-5 py-4 text-xs text-slate-500">{new Date(user.created_at).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><button className={`relative h-6 w-11 rounded-full transition disabled:cursor-not-allowed disabled:opacity-40 ${user.is_active ? 'bg-accent' : 'bg-slate-700'}`} type="button" role="switch" aria-checked={user.is_active} aria-label={`${user.is_active ? 'Suspend' : 'Activate'} ${user.email}`} disabled={isSelf || updatingUserId === user.id} onClick={() => onToggle(user)}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${user.is_active ? 'left-6' : 'left-1'}`} /></button></td></tr> })}{users.length === 0 && <tr><td className="px-5 py-12 text-center text-sm text-slate-500" colSpan={6}>No users match this search.</td></tr>}</tbody></table></div> }

function AuditTable({ logs, onInspect }: { logs: AdminAuditLog[]; onInspect: (log: AdminAuditLog) => void }) { return <div className="overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-border bg-bg/60 text-[11px] uppercase tracking-wider text-slate-600"><tr><th className="px-5 py-4 font-semibold">Timestamp</th><th className="px-5 py-4 font-semibold">Action</th><th className="px-5 py-4 font-semibold">Actor IP</th><th className="px-5 py-4 font-semibold">References</th><th className="px-5 py-4 text-right font-semibold">Details</th></tr></thead><tbody className="divide-y divide-border/70">{logs.map((log) => <tr className="text-sm text-slate-300" key={log.id}><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{new Date(log.created_at).toLocaleString()}</td><td className="px-5 py-4"><span className="rounded-md border border-primary/30 bg-primary/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-blue-300">{log.action.replaceAll('_', ' ')}</span></td><td className="px-5 py-4 font-mono text-xs text-slate-400">{log.ip_address ?? '—'}</td><td className="px-5 py-4 text-xs text-slate-500">{log.user_id ? `User ${log.user_id.slice(0, 8)}...` : log.device_id ? `Device ${log.device_id.slice(0, 8)}...` : 'System'}</td><td className="px-5 py-4 text-right"><button className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-semibold text-slate-300 hover:bg-card hover:text-slate-100" type="button" onClick={() => onInspect(log)}>Inspect <ChevronDown className="h-3.5 w-3.5" /></button></td></tr>)}{logs.length === 0 && <tr><td className="px-5 py-12 text-center text-sm text-slate-500" colSpan={5}>No audit events match this search.</td></tr>}</tbody></table></div> }

function AuditDetailsModal({ log, onClose }: { log: AdminAuditLog | null; onClose: () => void }) { if (!log) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="audit-details-title"><div className="w-full max-w-2xl rounded-2xl border border-border bg-surface shadow-2xl shadow-black/50"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Global audit ledger</p><h2 className="mt-1 text-lg font-semibold text-slate-50" id="audit-details-title">Event details</h2></div><button className="rounded-lg p-2 text-slate-500 hover:bg-card hover:text-slate-100" type="button" onClick={onClose} aria-label="Close audit details"><X className="h-5 w-5" /></button></div><div className="space-y-4 p-6"><div className="grid gap-3 text-sm sm:grid-cols-3"><Detail label="Action" value={log.action} /><Detail label="Timestamp" value={new Date(log.created_at).toLocaleString()} /><Detail label="Actor IP" value={log.ip_address ?? '—'} /></div><pre className="max-h-96 overflow-auto rounded-lg border border-border bg-bg p-4 text-xs leading-6 text-slate-300">{JSON.stringify(log.details, null, 2)}</pre></div></div></div> }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 break-all text-slate-300">{value}</p></div> }
